#!/bin/bash
# DecoupledActionExpert - All Repository Commands
# Generated by /collect-commands

# =============================================================================
# Setup
# =============================================================================

# Initialize git submodules and apply third-party patches
bash setup.sh

# Create/update conda environment and install all dependencies
bash env_install.sh

# =============================================================================
# Training Entry Point
# =============================================================================

# Main trainer (Hydra config system)
# python trainer.py --config-name=<config_name> [key=value overrides...]
# Example configs: dah_stage1_dp_c, dah_stage2_or_normal_dp_c, droid_dp_libero

# =============================================================================
# Debug (Quick Verification, 2 epochs)
# =============================================================================

# MimicGen debug
bash scripts/train/debug_dah_stage1.sh dp_c                        # Stage 1 pretraining
bash scripts/train/debug_dah_stage2.sh dp_c A <stage1-ckpt>        # Stage 2 fine-tuning
bash scripts/train/debug_dah_normal.sh dp_c A                      # Normal end-to-end

# LIBERO debug (DROID encoder)
bash scripts/train/debug_droid_dp_libero.sh                        # Normal training
bash scripts/train/debug_dah_stage1_droid_dp_t_libero.sh            # Stage 1, Transformer
bash scripts/train/debug_dah_stage1_droid_dp_t_film_libero.sh       # Stage 1, Transformer+FiLM
bash scripts/train/debug_dah_stage1_droid_dp_mlp_libero.sh          # Stage 1, MLP
bash scripts/train/debug_dah_stage2_droid_dp_t_libero.sh            # Stage 2, Transformer
bash scripts/train/debug_dah_stage2_droid_dp_t_film_libero.sh       # Stage 2, Transformer+FiLM
bash scripts/train/debug_dah_stage2_droid_dp_mlp_libero.sh          # Stage 2, MLP
bash scripts/train/debug_droid_dp_t_libero.sh                       # Normal, Transformer
bash scripts/train/debug_droid_dp_t_film_libero.sh                  # Normal, Transformer+FiLM
bash scripts/train/debug_droid_dp_mlp_libero.sh                     # Normal, MLP

# =============================================================================
# Training - MimicGen (Stage 1: Pretrain action head)
# =============================================================================

bash scripts/train/train_dah_stage1.sh dp_c                        # UNet backbone
bash scripts/train/train_dah_stage1.sh dp_mlp                      # MLP backbone
bash scripts/train/train_dah_stage1.sh dp_t                        # Transformer backbone
bash scripts/train/train_dah_stage1.sh dp_t_film                   # Transformer+FiLM backbone

# Ablations
bash scripts/train/train_dah_stage1_ablation.sh                    # Conditioning source ablation
bash scripts/train/train_dah_stage1_cond_ablation.sh               # Conditioning method ablation
bash scripts/train/train_dah_stage1_droid_data.sh                   # DROID data pretraining

# =============================================================================
# Training - MimicGen (Stage 2: Fine-tune with frozen backbone)
# =============================================================================

bash scripts/train/train_dah_stage2.sh dp_c A <stage1-ckpt>        # Per-task (A-H)
bash scripts/train/train_dah_stage2.sh dp_mlp A <stage1-ckpt>      # MLP per-task
bash scripts/train/train_dah_stage2_random_frozen.sh                # Random frozen baseline

# =============================================================================
# Training - MimicGen (Normal end-to-end)
# =============================================================================

bash scripts/train/train_dah_normal.sh dp_c A                      # Per-task (A-H)
bash scripts/train/train_dah_normal_cond_ablation.sh                # Conditioning method ablation

# =============================================================================
# Training - LIBERO (DROID encoder)
# =============================================================================

# Stage 1
bash scripts/train/train_dah_stage1_droid_dp_libero.sh              # UNet
bash scripts/train/train_dah_stage1_droid_dp_t_libero.sh            # Transformer
bash scripts/train/train_dah_stage1_droid_dp_t_film_libero.sh       # Transformer+FiLM
bash scripts/train/train_dah_stage1_droid_dp_mlp_libero.sh          # MLP
bash scripts/train/train_dah_stage1_droid_dp_droid_data.sh          # DROID data
bash scripts/train/train_dah_stage1_droid_dp_libero_combined.sh     # Combined data

# Stage 2
bash scripts/train/train_dah_stage2_droid_dp_libero.sh <ckpt>       # UNet
bash scripts/train/train_dah_stage2_droid_dp_libero_full.sh <ckpt>  # Full fine-tune
bash scripts/train/train_dah_stage2_droid_dp_t_libero.sh <ckpt>     # Transformer
bash scripts/train/train_dah_stage2_droid_dp_t_film_libero.sh <ckpt> # Transformer+FiLM
bash scripts/train/train_dah_stage2_droid_dp_mlp_libero.sh <ckpt>   # MLP

# Normal
bash scripts/train/train_droid_dp_libero.sh                         # UNet
bash scripts/train/train_droid_dp_t_libero.sh                       # Transformer
bash scripts/train/train_droid_dp_t_film_libero.sh                  # Transformer+FiLM
bash scripts/train/train_droid_dp_mlp_libero.sh                     # MLP

# =============================================================================
# SLURM (Cluster) - Paper Experiments
# =============================================================================

# Master experiment index
# scripts/slurm/IROS/ALL_PAPER_EXP.sh

# Individual SLURM scripts (set #SBATCH --account=<YOUR_ACCOUNT> first)
# scripts/slurm/IROS/IROS_dp_normal_mimicgen_pertask.sh             # V-A: Normal training
# scripts/slurm/IROS/IROS_dp_stage2_mimicgen_pertask.sh             # V-A: Decoupled training
# scripts/slurm/IROS/IROS_dp_stage2_mimicgen_pertask_droid_pretrain.sh  # V-B: DROID transfer
# scripts/slurm/IROS/IROS_dp_stage2_mimicgen_pertask_ablation_cond_source.sh  # V-D: Cond source
# scripts/slurm/IROS/IROS_dp_stage2_mimicgen_pertask_ablation_cond_method.sh  # V-E: Cond method

# =============================================================================
# Utilities
# =============================================================================

# Create a random checkpoint for testing
python scripts/create_random_ckpt.py
